/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mm_messagepasser;

import java.util.logging.Level;
import java.util.logging.Logger;
import mmcorej.StrVector;

/**
 *
 * @author Sunil
 */
public class msg_set_panel extends javax.swing.JPanel {
    msg_passer_hostframe parent_ = null;
    
    /**
     * Creates new form msg_set_panel
     */
    public msg_set_panel() {
        initComponents();
    }

    public void set_parent(msg_passer_hostframe parent_frame){
        parent_ = parent_frame;
    }    

    public void update_dev_list() {
        msg_dev_combo.removeAllItems();
        try {
            StrVector msg_devs = parent_.core_.getAvailableDevices(parent_.core_.getDeviceLibrary("Plugin message passer"));
            System.out.println(msg_devs);
            System.out.println(msg_devs.size());
            if(msg_devs.size()>0){
                for(String dev : msg_devs){
                    msg_dev_combo.addItem(dev);
                }
                msg_dev_combo.setSelectedIndex(0);
            }
        } catch (Exception ex) {
            Logger.getLogger(msg_set_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msg_to_set_area = new javax.swing.JTextArea();
        set_msg = new javax.swing.JButton();
        msg_dev_combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        msg_to_set_area.setColumns(20);
        msg_to_set_area.setRows(5);
        jScrollPane1.setViewportView(msg_to_set_area);

        set_msg.setText("Set the message");
        set_msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_msgActionPerformed(evt);
            }
        });

        msg_dev_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Messenger device: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msg_dev_combo, 0, 164, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(set_msg)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set_msg)
                    .addComponent(msg_dev_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void set_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_msgActionPerformed
        try {
            parent_.core_.setProperty(msg_dev_combo.getSelectedItem().toString(), "Message value", parent_.dp_json_escaper(msg_to_set_area.getText()));
            parent_.gui_.app().refreshGUI();
        } catch (Exception ex) {
            Logger.getLogger(msg_set_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_set_msgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> msg_dev_combo;
    private javax.swing.JTextArea msg_to_set_area;
    private javax.swing.JButton set_msg;
    // End of variables declaration//GEN-END:variables
}
